backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

site_url: "https://pafoi.org"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        name: "home"
        label: "Home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "content/about.md"
        name: "about"
        label: "About"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "content/start/_index.md"
        name: "start"
        label: "Start"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }

      - file: "content/ideas/_index.md"
        name: "ideas"
        label: "Ideas & Projects"
        fields:
          - { label: "Title", name: "title", widget: "string" }
